version: "3.7"

volumes:
  rabbitmq_volume:


services:
  rabbitmq:
    image: rabbitmq:3.12.1-management-alpine
    restart: unless-stopped
    hostname: rabbitmq
    ports:
      - 1883:1883
      - 8883:8883
      - 15675:15675
      - 15676:15676
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/
      - ./configs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
